### ISSUE TITLE
Cannot add a number for new user name

### ISSUE THREAD

**Issue by polytan02** [YunoHost/yunohost-admin#104]
Hi,

If I create a new user (such as user3), I can put a number for the "username", but not for the "first name" (prénom).

**Comment by jeromelebleu** [comment]
It's due to the regex pattern on the first name - which allows only alphabetic characters, but it's maybe too restrictive and should be fixed. Anyway, this is part of the https://github.com/YunoHost/moulinette-yunohost repository and not the admin-js.
I'll close this issue, please see: https://github.com/YunoHost/moulinette-yunohost/issues/21

**Comment by polytan02** [comment]
Thanks.
