### ISSUE TITLE
Allow custom dyndns services to add subdomains easily

### ISSUE THREAD

**Issue by scith** [YunoHost/yunohost-admin#108]
Hello,
Is it possible to add one's own domain in the automatic domain creation?
The current list has only _.nohost.me_ and _.noho.st_

I would like to have my own domain with a dyndns and be able to add it in the list so I can create custom subdomains on the fly.

Would it be possible to quickly add new dyndns providers? Also how can I set up a dyndns service on my own server?

Thanks

**Comment by M5oul** [comment]
Here is [dynette repository](https://github.com/YunoHost/dynette) to permit you create you own instance of dyndns service based on other domain name.

**Comment by scith** [comment]
Thanks. However I am not really understanding how it works: 
- I have a host server at *test.com* which I would like to use as a DNS (so users can create *subdomain.test.com* via their admin panels)
- On this host server, I install the dynette using the instructions in the git. It comes with postgresql right?
- What should I then setup on the client server to allow users to create their subdomains at *test.com* within the admin interface?
- If I want to remove a subdomain like you do when users ask in the forum, should I do it directly from within the postgresql database?
- Is it possible to delete the subdomain on the host server when the client delete the domain on its interface? This way we won't have to manually delete the subdomains like you do when asked in the forum...

Sorry for all these questions and thanks...

**Comment by alexAubin** [comment]
The question is pretty legitim though, and it would be great to be able to start your own dyndns / dynette server by simply installing an app on your yunohost instance (+ maybe a few DNS tweaks). However being able to do so at the moment still require some technical skills. 

There's a [dynette_ynh](https://github.com/YunoHost-Apps/dynette_ynh) to ease installation, but other aspects are so far not well documented I think (like, how to configure your 'root' DNS ? what are the precautions and implication of having your own dyndns/dynette server ?). 

Anyway, on yunohost's side, it should be possible/"easy" to specify a custom dyndns provider in the command line. Other than that, imho this issue is off-topic for this repo. But feel free to reopen the question on redmine or on dynette/dynette_ynh if needed.
